config/routes.rb
Rails.application.routes.draw do
  resources :peliculas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  before_action :set_pelicula, only: [:show, :edit, :update, :destroy]

  # GET /peliculas
  # GET /peliculas.json
  def index
    @peliculas = Pelicula.all
  end

  # GET /peliculas/1
  # GET /peliculas/1.json
  def show
  end

  # GET /peliculas/new
  def new
    @pelicula = Pelicula.new
  end

  # GET /peliculas/1/edit
  def edit
  end

  # POST /peliculas
  # POST /peliculas.json
  def create
    @pelicula = Pelicula.new(pelicula_params)

    respond_to do |format|
      if @pelicula.save
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully created.' }
        format.json { render :show, status: :created, location: @pelicula }
      else
        format.html { render :new }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peliculas/1
  # PATCH/PUT /peliculas/1.json
  def update
    respond_to do |format|
      if @pelicula.update(pelicula_params)
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully updated.' }
        format.json { render :show, status: :ok, location: @pelicula }
      else
        format.html { render :edit }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peliculas/1
  # DELETE /peliculas/1.json
  def destroy
    @pelicula.destroy
    respond_to do |format|
      format.html { redirect_to peliculas_url, notice: 'Pelicula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelicula
      @pelicula = Pelicula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pelicula_params
      params.require(:pelicula).permit(:titulo, :genero, :sinopsis, :pais, :duracion, :calificacion, :director)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peliculas/_form.html.erb
<%= form_for(pelicula) do |f| %>
  <% if pelicula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pelicula.errors.count, "error") %> prohibited this pelicula from being saved:</h2>

      <ul>
      <% pelicula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="form-control">
  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :genero %>
    <%= f.text_field :genero %>
  </div>

  <div class="field">
    <%= f.label :sinopsis %>
    <%= f.text_area :sinopsis %>
  </div>

  <div class="field">
    <%= f.label :pais %>
    <%= f.text_field :pais %>
  </div>

  <div class="field">
    <%= f.label :duracion %>
    <%= f.text_field :duracion %>
  </div>

  <div class="field">
    <%= f.label :calificacion %>
    <%= f.text_field :calificacion %>
  </div>

  <div class="field">
    <%= f.label :director %>
    <%= f.text_field :director %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
 </div>
</div>  
<% end %>

app/views/peliculas/edit.html.erb
<h1>Editing Pelicula</h1>

<%= render 'form', pelicula: @pelicula %>

<%= link_to 'Mostrar', @pelicula , class:'btn btn-info'%> |
<%= link_to 'Volver', peliculas_path , class:'btn btn-info'%>

app/views/peliculas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peliculas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Genero</th>
      <th>Sinopsis</th>
      <th>Pais</th>
      <th>Duracion</th>
      <th>Calificacion</th>
      <th>Director</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peliculas.each do |pelicula| %>
      <tr>
        <td><%= pelicula.titulo %></td>
        <td><%= pelicula.genero %></td>
        <td><%= pelicula.sinopsis %></td>
        <td><%= pelicula.pais %></td>
        <td><%= pelicula.duracion %></td>
        <td><%= pelicula.calificacion %></td>
        <td><%= pelicula.director %></td>
        <td><%= link_to 'Mostrar', pelicula , class:'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_pelicula_path(pelicula) , class:'btn btn-default' %></td>
        <td><%= link_to 'Eliminar', pelicula, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Pelicula', new_pelicula_path , class:'btn btn-info' %>

app/views/peliculas/new.html.erb
<h1>Nueva Pelicula</h1>

<%= render 'form', pelicula: @pelicula , class:'form-group'%>

<%= link_to 'Volver', peliculas_path, class:'btn btn-default' %>

app/views/peliculas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @pelicula.titulo %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @pelicula.genero %>
</p>

<p>
  <strong>Sinopsis:</strong>
  <%= @pelicula.sinopsis %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @pelicula.pais %>
</p>

<p>
  <strong>Duracion:</strong>
  <%= @pelicula.duracion %>
</p>

<p>
  <strong>Calificacion:</strong>
  <%= @pelicula.calificacion %>
</p>

<p>
  <strong>Director:</strong>
  <%= @pelicula.director %>
</p>

<%= link_to 'Edit', edit_pelicula_path(@pelicula) %> |
<%= link_to 'Back', peliculas_path %>